/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import clases.Cliente;
import clases.ConexionExist;
import clases.Empleado;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.*;

/**
 * @author omega
 */
public class PanelEditarCliente extends javax.swing.JPanel {
    JPanel content;
    int id;
    ConexionExist conexion = new ConexionExist();

    /**
     * Creates new form PanelEditarCliente
     */
    public PanelEditarCliente(JPanel content, List<Cliente> clientes, int id) {
        initComponents();
        this.content = content;
        this.id = id;

        for (Cliente cliente : clientes) {
            if (cliente.getId() == id) {
                nombreField.setText(cliente.getNombre());
                telefonoField.setText(String.valueOf(cliente.getTelefono()));
                emailField.setText(cliente.getEmail());
            }
        }
        if (nombreField.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Ha surgido un problema al cargar los datos.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        telefonoField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        editarBoton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cancelarBoton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EDITAR CLIENTE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 260, 20));

        nombreField.setBackground(new java.awt.Color(204, 204, 204));
        nombreField.setBorder(null);
        add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 300, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 300, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Telefono:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 260, 20));

        telefonoField.setBackground(new java.awt.Color(204, 204, 204));
        telefonoField.setBorder(null);
        add(telefonoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 300, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 300, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 260, 20));

        emailField.setBackground(new java.awt.Color(204, 204, 204));
        emailField.setBorder(null);
        add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 300, 20));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 300, -1));

        editarBoton.setBackground(new java.awt.Color(57, 57, 58));
        editarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editarBotonMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(57, 57, 58));
        jLabel6.setForeground(new java.awt.Color(219, 219, 219));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Editar Cliente");

        javax.swing.GroupLayout editarBotonLayout = new javax.swing.GroupLayout(editarBoton);
        editarBoton.setLayout(editarBotonLayout);
        editarBotonLayout.setHorizontalGroup(
            editarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        editarBotonLayout.setVerticalGroup(
            editarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(editarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 160, 50));

        cancelarBoton.setBackground(new java.awt.Color(57, 57, 58));
        cancelarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cancelarBotonMousePressed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(219, 219, 219));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cancelar");

        javax.swing.GroupLayout cancelarBotonLayout = new javax.swing.GroupLayout(cancelarBoton);
        cancelarBoton.setLayout(cancelarBotonLayout);
        cancelarBotonLayout.setHorizontalGroup(
            cancelarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        cancelarBotonLayout.setVerticalGroup(
            cancelarBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        add(cancelarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 160, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarBotonMousePressed
        PanelClientes frame = new PanelClientes(content);
        frame.setSize(830, 550);
        frame.setLocation(0, 0);
        content.removeAll();
        content.add(frame, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_cancelarBotonMousePressed

    private void editarBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarBotonMousePressed
        try {
            int telefono = Integer.parseInt(telefonoField.getText());
            if (nombreField.getText().isBlank() || emailField.getText().isBlank() || String.valueOf(telefono).length() != 9){
                JOptionPane.showMessageDialog(null, "Compruebe que los datos son correctos");
            } else {
                Cliente updateCli = new Cliente(id, nombreField.getText(), telefono, emailField.getText());
                conexion.editarCliente(updateCli);
                JOptionPane.showMessageDialog(null, "El cliente se ha editado corectamente.");
                PanelClientes frame = new PanelClientes(content);
                frame.setSize(830,550);
                frame.setLocation(0,0);
                content.removeAll();
                content.add(frame, BorderLayout.CENTER);
                content.revalidate();
                content.repaint();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Introduce valores correctos o comprueba el numero de telefono.");
        }
    }//GEN-LAST:event_editarBotonMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cancelarBoton;
    private javax.swing.JPanel editarBoton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField telefonoField;
    // End of variables declaration//GEN-END:variables
}
